[2024-10-15T03:35:08.975+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-15T03:35:08.983+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: simple_dag.print_hello_world manual__2024-10-15T03:35:02.254203+00:00 [queued]>
[2024-10-15T03:35:08.987+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: simple_dag.print_hello_world manual__2024-10-15T03:35:02.254203+00:00 [queued]>
[2024-10-15T03:35:08.988+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2024-10-15T03:35:08.995+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): print_hello_world> on 2024-10-15 03:35:02.254203+00:00
[2024-10-15T03:35:08.999+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=59356) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-15T03:35:08.999+0000] {standard_task_runner.py:72} INFO - Started process 59363 to run task
[2024-10-15T03:35:08.999+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'simple_dag', 'print_hello_world', 'manual__2024-10-15T03:35:02.254203+00:00', '--job-id', '115', '--raw', '--subdir', 'DAGS_FOLDER/chinedu_sample.py', '--cfg-path', '/tmp/tmpxberg2jn']
[2024-10-15T03:35:09.000+0000] {standard_task_runner.py:105} INFO - Job 115: Subtask print_hello_world
[2024-10-15T03:35:09.033+0000] {task_command.py:467} INFO - Running <TaskInstance: simple_dag.print_hello_world manual__2024-10-15T03:35:02.254203+00:00 [running]> on host e73bcfa50a08
[2024-10-15T03:35:09.071+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='simple_dag' AIRFLOW_CTX_TASK_ID='print_hello_world' AIRFLOW_CTX_EXECUTION_DATE='2024-10-15T03:35:02.254203+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-15T03:35:02.254203+00:00'
[2024-10-15T03:35:09.075+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-10-15T03:35:09.075+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-10-15T03:35:09.076+0000] {logging_mixin.py:190} INFO - Current task name:print_hello_world state:running start_date:2024-10-15 03:35:08.984315+00:00
[2024-10-15T03:35:09.077+0000] {logging_mixin.py:190} INFO - Dag name:simple_dag and current dag run status:running
[2024-10-15T03:35:09.081+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-15T03:35:09.081+0000] {logging_mixin.py:190} INFO - Hello, Airflow!
[2024-10-15T03:35:09.082+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/chinedu_sample.py", line 52, in hello_world
    raise Exception('The task hals failed intentionally')
Exception: The task hals failed intentionally
[2024-10-15T03:35:09.091+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-10-15T03:35:09.091+0000] {logging_mixin.py:190} INFO - Task start:2024-10-15 03:35:08.984315+00:00 end:2024-10-15 03:35:09.090920+00:00 duration:0.106605
[2024-10-15T03:35:09.092+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): print_hello_world> dag:<DAG: simple_dag> dagrun:<DagRun simple_dag @ 2024-10-15 03:35:02.254203+00:00: manual__2024-10-15T03:35:02.254203+00:00, state:running, queued_at: 2024-10-15 03:35:02.265683+00:00. externally triggered: True>
[2024-10-15T03:35:09.094+0000] {logging_mixin.py:190} INFO - Failure caused by The task hals failed intentionally
[2024-10-15T03:35:09.095+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=simple_dag, task_id=print_hello_world, run_id=manual__2024-10-15T03:35:02.254203+00:00, execution_date=20241015T033502, start_date=20241015T033508, end_date=20241015T033509
[2024-10-15T03:35:09.096+0000] {taskinstance.py:1563} INFO - Executing callback at index 0: send_rocketchat_failure_alert
[2024-10-15T03:35:09.909+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-15T03:35:09.910+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 115 for task print_hello_world (The task hals failed intentionally; 59363)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/chinedu_sample.py", line 52, in hello_world
    raise Exception('The task hals failed intentionally')
Exception: The task hals failed intentionally
[2024-10-15T03:35:09.930+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-15T03:35:09.939+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-15T03:35:09.940+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
