[2024-10-14T09:29:13.490+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-14T09:29:13.496+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: simple_dag.print_hello_world scheduled__2024-10-14T09:28:00+00:00 [queued]>
[2024-10-14T09:29:13.500+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: simple_dag.print_hello_world scheduled__2024-10-14T09:28:00+00:00 [queued]>
[2024-10-14T09:29:13.500+0000] {taskinstance.py:2865} INFO - Starting attempt 3 of 4
[2024-10-14T09:29:13.506+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): print_hello_world> on 2024-10-14 09:28:00+00:00
[2024-10-14T09:29:13.510+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=20810) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-14T09:29:13.510+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'simple_dag', 'print_hello_world', 'scheduled__2024-10-14T09:28:00+00:00', '--job-id', '101', '--raw', '--subdir', 'DAGS_FOLDER/chinedu_sample.py', '--cfg-path', '/tmp/tmpjhxj3c48']
[2024-10-14T09:29:13.511+0000] {standard_task_runner.py:72} INFO - Started process 20811 to run task
[2024-10-14T09:29:13.511+0000] {standard_task_runner.py:105} INFO - Job 101: Subtask print_hello_world
[2024-10-14T09:29:13.541+0000] {task_command.py:467} INFO - Running <TaskInstance: simple_dag.print_hello_world scheduled__2024-10-14T09:28:00+00:00 [running]> on host 53481863f797
[2024-10-14T09:29:13.578+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='simple_dag' AIRFLOW_CTX_TASK_ID='print_hello_world' AIRFLOW_CTX_EXECUTION_DATE='2024-10-14T09:28:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-14T09:28:00+00:00'
[2024-10-14T09:29:13.579+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-10-14T09:29:13.580+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-10-14T09:29:13.580+0000] {logging_mixin.py:190} INFO - Current task name:print_hello_world state:running start_date:2024-10-14 09:29:13.497302+00:00
[2024-10-14T09:29:13.580+0000] {logging_mixin.py:190} INFO - Dag name:simple_dag and current dag run status:running
[2024-10-14T09:29:13.580+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-14T09:29:13.580+0000] {logging_mixin.py:190} INFO - Hello, Airflow!
[2024-10-14T09:29:13.581+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/chinedu_sample.py", line 24, in hello_world
    raise Exception('The task hals failed intentionally')
Exception: The task hals failed intentionally
[2024-10-14T09:29:13.587+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-10-14T09:29:13.587+0000] {logging_mixin.py:190} INFO - Task start:2024-10-14 09:29:13.497302+00:00 end:2024-10-14 09:29:13.586812+00:00 duration:0.08951
[2024-10-14T09:29:13.587+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): print_hello_world> dag:<DAG: simple_dag> dagrun:<DagRun simple_dag @ 2024-10-14 09:28:00+00:00: scheduled__2024-10-14T09:28:00+00:00, state:running, queued_at: 2024-10-14 09:29:00.911757+00:00. externally triggered: False>
[2024-10-14T09:29:13.587+0000] {logging_mixin.py:190} INFO - Failure caused by The task hals failed intentionally
[2024-10-14T09:29:13.587+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=simple_dag, task_id=print_hello_world, run_id=scheduled__2024-10-14T09:28:00+00:00, execution_date=20241014T092800, start_date=20241014T092913, end_date=20241014T092913
[2024-10-14T09:29:13.593+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-14T09:29:13.593+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 101 for task print_hello_world (The task hals failed intentionally; 20811)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/chinedu_sample.py", line 24, in hello_world
    raise Exception('The task hals failed intentionally')
Exception: The task hals failed intentionally
[2024-10-14T09:29:13.614+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-14T09:29:13.622+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-14T09:29:13.623+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
